name: geoflutterfire2
description:
  GeoFlutterFire2 is an open-source library that allows you to store and query firestore documents
  based on their geographic location.
version: 2.3.16
homepage: https://github.com/beerstorm-net/geoflutterfire2

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.0.1
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
